global:
  scrape_interval: 5s
  scrape_timeout: 4s
  evaluation_interval: 5s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: ['localhost:9090']

- job_name: node
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets: ['node-exporter:9100']
  
- job_name: cadvisor
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets: ['cadvisor:8080']
