services:
  overseerr:
    container_name: overseerr
    image: ghcr.io/hotio/overseerr:release-1.33.2
    ports:
      - "5055:5055"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /mnt/user/appdata/overseerr:/config
    restart: unless-stopped
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
    name: arr_network
