name: Unraid - memos

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (up or down)'
        required: true
        default: 'up'

jobs:
  manage:
    runs-on: unraid
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set Environment Variables
        run: |
          echo "UNRAID_APPDATA_PATH=${{ vars.UNRAID_APPDATA_PATH }}" >> $GITHUB_ENV
        
      - name: Perform Docker Compose action
        run: |
          if [ "${{ github.event.inputs.action }}" == "up" ]; then
            docker compose -f unraid/memos.yml up -d
          elif [ "${{ github.event.inputs.action }}" == "down" ]; then
            docker compose -f unraid/memos.yml down
          else
            echo "Invalid action specified."
            exit 1
          fi
